### ISSUE TITLE
moving repos to this org

### ISSUE THREAD

**Issue by ghost** [workshopper/org#11]
I would like to move these repos to this org:
- adventure
- stream-adventure
- browserify-adventure
- regex-adventure

Thanks!

**Comment by martinheidegger** [comment]
I invited you to the organization. You should be able to simply transfer the packages.

**Comment by llkats** [comment]
Thank you so much, @substack!!!

**Comment by ghost** [comment]
I have moved these repos over. Is there a list of npm maintainers I should add?

**Comment by martinheidegger** [comment]
@julianduque & @tdd are "release-managers" atm.

**Comment by ghost** [comment]
Added. Thanks.
