### ISSUE TITLE
NPM organization for NodeSchool

### ISSUE THREAD

**Issue by martinheidegger** [workshopper/org#12]
When NPM started offering namespaces I took the liberty and registered the nodeschool namespace. However: I think it would be cool if we had a "nodeschool" organization. I guess that would make publishing NodeSchool workshoppers easier, right?

**Comment by martinheidegger** [comment]
cc. @isaacs @ashleygwilliams

**Comment by bengl** [comment]
Hmm, looks like this may already be taken. https://www.npmjs.com/~nodeschool Maybe it's worth reaching out via the email address there?

**Comment by martinheidegger** [comment]
@bengl 

> I took the liberty and registered the nodeschool namespace.

**Comment by bengl** [comment]
Ah! Awesome!

**Comment by martinheidegger** [comment]
The problem is that a npm organization costs $7 / user / month - a lot of dough for this org. https://www.npmjs.com/pricing

**Comment by isaacs** [comment]
@martinheidegger Someday, in the not too distant future, there will come a time when it will be possible to create an organization that may only publish open source packages, and lacks some other "pro" features, but does not cost any money.

In the slightly less distant future, we will want to beta test something like a free OSS-only organization, and it may have some jank and clunk, but once the initial hurdle is crossed, should be fully functional.  Would you be interested in being such an organization?  I think Node School would be a perfect fit.

**Comment by martinheidegger** [comment]
@isaacs  Absolutely!

**Comment by isaacs** [comment]
Ok.  It'll be a little while (probably a few months, idk, I'm just the product guy, I'm not doing the actual work.)

If you need it more urgently, just sign up for an org and flip the bit to "unpaid" on all the users you add, so that it's only $14 a month.  Then we can give you a discount to make that bit go away.  (That's extra janky though, because you have to remember to not accidentally add any paid users; once we are done cleaning up the payment logic, it'll be way simpler.)

**Comment by martinheidegger** [comment]
@isaacs Sorry for coming back at this so late. _(Had a few things to work through)_. This org seems to be useful! Than you for the suggestion. @workshopper/deploy is the team in charge of org-wide deployments. @workshopper/deploy What do you think?

**Comment by isaacs** [comment]
@martinheidegger Stay tuned.  (Weeks, not months.)  At this point, it's close enough to release to just wait rather than sign up and downgrade or refund the account later.

**Comment by kalinchernev** [comment]
And [organizations are now free for open source](https://medium.com/npm-inc/announcing-free-orgs-48b5f9b39510#.3ftqxxhf7).

**Comment by martinheidegger** [comment]
I created the workshopper org on NPM https://www.npmjs.com/org/workshopper/members and invited @workshopper/deploy to it.
