### ISSUE TITLE
Motto

### ISSUE THREAD

**Issue by jpwesselink** [workshopper/org#17]
I have taken the liberty to come up with a motto.

> # Build to teach. Teach to build.

I think this reflects this organisation's purpose very well.

**Comment by martinheidegger** [comment]
👍  PR → Readme!

**Comment by martinheidegger** [comment]
Added motto as description of workshopper on the github org: 
![screenshot 2016-10-30 22 04 41](https://cloud.githubusercontent.com/assets/914122/19836733/f43d909c-9eec-11e6-9713-6d776be3e62d.png)
