### ISSUE TITLE
Pinned repos

### ISSUE THREAD

**Issue by denysdovhan** [workshopper/org#20]
Since GitHub gives us ability to pin repos for organization. Maybe we should pin our core workshoppers? What do you think?

**Comment by martinheidegger** [comment]
Sure!

**Comment by denysdovhan** [comment]
@martinheidegger I've pinned these workshoppers:

![image](https://cloud.githubusercontent.com/assets/3459374/19829026/36b7d55e-9ddf-11e6-8c63-f778e948b66e.png)

Feel free to close this issue, if everything is okay.

**Comment by martinheidegger** [comment]
I am sure that "requests for improvement" will come some day, until then lets say Thanks! and Good work!
