### ISSUE TITLE
Workshoppers for other programming languages

### ISSUE THREAD

**Issue by jsturtevant** [workshopper/org#24]
Would it be possible to create a workshopper for another language (python/ruby/c#) using the workshopper framework?

**Comment by denysdovhan** [comment]
@jsturtevant I'm sure it would be as easy as creating any other workshopper. Actually, there are a bunch of such workshoppers:

* [shader-school](https://github.com/stackgl/shader-school)
* [introtowebgl](https://github.com/alexmackey/IntroToWebGLWithThreeJS)
* [webgl-workshop](https://github.com/stackgl/webgl-workshop)
* [learnuv](https://github.com/thlorenz/learnuv)

**Comment by martinheidegger** [comment]
@denysdovhan is maybe a little too humble. His workshopper [learnyoubash](https://github.com/denysdovhan/learnyoubash) also teaches bash (programming language,right?)

**Comment by martinheidegger** [comment]
Oh, there is one thing worth mentioning: While it is perfectly possible to implement a workshopper for another language, the current [syntax highlighting is very limited](https://github.com/firede/msee/issues/44)

**Comment by jsturtevant** [comment]
Great. Thanks for the links!
