### ISSUE TITLE
Merge Into NodeSchool: International Contribution Day!

### ISSUE THREAD

**Issue by hackygolucky** [workshopper/org#26]
(cross-posted to the [NodeSchool org](https://github.com/nodeschool/organizers/issues/422))

NodeSchool is so important to the history(and future) of Node.js, so I've been chatting with some organizers and wanted to get everyone's take.  The idea:

This would be in interesting hybrid event. It has the power to teach some people how to contribute in a way they may not have yet, but also encourages a day of focusing on giving back to NodeSchool. The workshoppers are such an incredible contribution to Node.js that so many worldwide events are dependent on. We want to help ensure future health, if possible. Get some more energy into it.

### The plan for Merge Into NodeSchool: International Contribution Day
- Identify workshoppers that need the most help, prioritizing Core workshoppers and then supplemental
- Prior to international event, have knowledgeable mentors/contributors tag issues for each workshopper with beginner/intermediate/advanced
- Pick a date!(months away)
- Reach out to workshop authors to let them know this is going to happen, and offer help in reviewing and merging all of the PRs that come out of this.
- Prep mentors/organizers in a hangout prior to event day
- Document instructions for "How to submit a PR", "How to Contribute to NodeSchool Workshoppers", "How to Workshopper"(this is a lot of prep work!)
- Figure out better logistics of worldwide streaming across locations
- Slack channel with easy sign-up for participants/community(we may have this solved for Node.js overall soon either in IRC/Slack)
- Advertise out this event and have a list of participating sites(on NodeSchool.io and GitHub repo)
- Create a sponsor prospectus for local events to be able to copy and send out if they want things/food/bev for the event
- Contribution-day repo & team working on it(for coordinating and people needing to ask for help)
- Installfest and Devfest instructions so people can try to not take down wifi at the event(but this is also good for DURING the event)
- Swag that Node.js Foundation can cover and send to individual sites with enough time.
- What's missing?

To make this welcoming to everyone, those who are newer(maybe attended NodeSchool and have never mentored but want to help) can pair with someone more knowledgeable so they are able to contribute. Everyone learns! Everyone helps! @jpwesselink inspired this one for sure after I'd mentioned I had concern that this would not be exciting to folks who don't mentor or aren't as experienced developers.

We've gotten a little allocation from the Node.js Foundation for
- swag to send to participating sites and cover shipping costs
- streaming of events(we will figure out these logistics later)

Next step would be to plan a meeting or workshopper folks and active NodeSchool organizers to iron this out a bit.

*What do y'all think?*

**Comment by martinheidegger** [comment]
I am steadily working on cleaning up and structuring workshoppers, any help from this is welcome. I have no idea what "Merge into NodeSchool" should mean though.

**Comment by watilde** [comment]
I also started working for this on `how-to-npm` to adjust PRs, and `nodejs-ja` to support translation.

**Comment by martinheidegger** [comment]
The meeting seems to be planned in https://github.com/nodeschool/organizers/issues/422, closing this issue to avoid confusion.
