### ISSUE TITLE
Git-it Things

### ISSUE THREAD

**Issue by jlord** [workshopper/org#27]
Hi! 👋 

I wanted to see about two things:

1. Git-it is being used enough (yay!) that I'm exceeding my free account limit with an email service I use for the server that works with users. It's already over for this month FYI but I have an idea for how to change it so that I'm not relying on that service (yay!) but I won't be able to work on it for at least couple weeks, also FYI.

2. The Git-it linked to here is the terminal version that is similar to the other NodeSchool workshoppers. But because many people trying to learn Git (and using Git-it) aren't also trying to leran Node and because there are more visual components to how Git-it works, I've updated it to be a standalone desktop app. This is the version I'm actively maintaining. So, should we update the ink here to use that version or is there reason to keep using the terminal format one for Git-it?

Thankssssssss :heart: 🍕 🐱

**Comment by jlord** [comment]
I'm not really sure who to ping on this because I'm not really sure if there is any one particular chapter that is most actively using Git-it?

**Comment by jpwesselink** [comment]
Hi! NodeSchool contrib here 🤘🏻 Since git-it is advertized as core workshopper I think a lot of chapters are using it. Does exceeding account limit mean using git-it is giving errors right now?

**Comment by jlord** [comment]
>  Does exceeding account limit mean using git-it is giving errors right now?

Git-it is still complete-able, but the challenges involved with adding @reporobot as a collaborator and pull in its changes will have to be skipped.

**Comment by llkats** [comment]
I think we should change the link to be the actively-maintained version. We could also consider removing Git-it from the core workshoppers and put it (probably at the top) of the Electives. Is git knowledge strictly necessary to use Node?

Regardless, we should be promoting workshoppers that are actively maintained. Thanks for all your (past and future) work, @jlord -- so many people have learned git through your efforts!

**Comment by stefanmirck** [comment]
I agree with @llkats that we should link to the actively-maintained version, even if that means moving away from the CLI. However, IMHO, I do think we should keep it as a core workshopper. Git-it teaches essential skills needed for (open-source) software development and as such fits perfectly as a core workshopper. More so than Elementary Electron, I would say.

**Comment by jlord** [comment]
Awesome, thanks y'all ❤️ 

I can make a PR to update which Git-it it links to 👍 and will leave it in core for now, of course, if folks decide later to move it that's cool too 👌

**Comment by jpwesselink** [comment]
@jlord what do you need to keep it working as it is right now?

**Comment by jpwesselink** [comment]
Oh hey, and thanks so much for making this btw :)

**Comment by jlord** [comment]
> what do you need to keep it working as it is right now?

It's using this service [Cloudmailin](https://www.cloudmailin.com/plans) which sends emails (that @reporobot gets from GitHub to notify when it's been added as a collaborator to a repo) to the server which triggers a series of other events from the server. 

I'm on the free plan which is capped at 200 emails a month, which has been fine for a long time but I've noticed it has been getting surpassed recently. 

To make it work right now I'd need to upgrade to the not free plan...which as I'm thinking about this now I think I might as well do to get it through until I find time to build a new way to get notifications to the server without this service (it seems like I can do it with a Gmail account and google app scripts).

I've been paying for the server that @reporobot lives on and not that it's a great deal of money but would just like to not add another paid service :)

**Comment by jlord** [comment]
Update: I just logged in and even though it sent me an email saying that I'd gone over the 200 limit, it's still accepting them (and am at 219 now) soooooo actually maybe even though it's been surpassing it, they aren't shutting me down :)

I'll keep monitoring it and make sure it doesn't actually stop working and it would be nice if it would continue working until I could eliminate the need for it 🍕 

<img width="271" alt="screen shot 2017-03-16 at 4 33 12 pm" src="https://cloud.githubusercontent.com/assets/1305617/24017462/83b5eba4-0a66-11e7-8c79-7f5b111e0cb0.png">

<img width="846" alt="screen shot 2017-03-16 at 4 35 16 pm" src="https://cloud.githubusercontent.com/assets/1305617/24017472/922fb73c-0a66-11e7-9f00-c3adddf0d184.png">

**Comment by jpwesselink** [comment]
Thanks so much :) In the meantime we can cook up a solution for this :)

**Comment by llkats** [comment]
@jlord you are so generous!! I feel like maybe the community should help you out a bit, though, so it's not just on your shoulders! Even if you re-do the email service, we could still pitch in on the hosting costs.

Pinging @hackygolucky and @mikeal, hi! Would it be possible that the Node Foundation might help support @jlord's modest expenses for hosting `git-it`?

**Comment by mikeal** [comment]
The foundation is using a comp'd mailgun account, we could probably move you over to that ;)

**Comment by martinheidegger** [comment]
There is a lot in here that is awesome. However just that I get this right: this does really seem to be an NodeSchool issue right? (git-it is not in the workshopper-github-org?!)

**Comment by martinheidegger** [comment]
It seems like there is nothing that needs to be done here. Closing the issue. Please feel free to reopen if I mistook this.
