### ISSUE TITLE
Any arguments against a workshopper-adventure?

### ISSUE THREAD

**Issue by martinheidegger** [workshopper/org#3]
Before this whole workshopper move project I was working on a api-combination of workshopper & adventure called "workshopper-adventure" - there is even a PR on this. Due to the lack of communication in this org I am considering to take action by myself and publish it as a fork in the workshopper-adventure repo of the workshopper org and put a statement in the workshopper repo that it's not maintained for the time being. Is that a hasty step? Should we start finding a different communication approach?

**Comment by martinheidegger** [comment]
Will create workshopper-adventure.

**Comment by bcomnes** [comment]
:+1:
