### ISSUE TITLE
Maintainer for goingnative

### ISSUE THREAD

**Issue by AnshulMalik** [workshopper/org#32]
I was going through this list: https://github.com/workshopper/org/blob/master/STRUCTURE.md

And I found that there is no active maintainer for goingnative, I'd like to help there :)

**Comment by martinheidegger** [comment]
Added you as maintainer, you should be having full admin access. Please let me know if you have problems accessing something.

**Comment by AnshulMalik** [comment]
Perfect Thanks :) I'll try my best.
