### ISSUE TITLE
Getting added as a member of workshopper

### ISSUE THREAD

**Issue by gyaresu** [workshopper/org#34]
Hi!

I was hoping to get added as a member of the workshopper org so I can start cleaning up PR's and documentation.

I'm a member of the [Nodeschool](https://github.com/orgs/nodeschool/people?utf8=%E2%9C%93&query=gareth) org. And more specifically we run nodeschool events at  [Vancouver](https://github.com/nodeschool/vancouver).

I've read the [contributing](https://github.com/workshopper/org/blob/master/CONTRIBUTING.md) rules and will abide by them.

Any questions, please don't hesitate to ask.

Cheers

Gareth

**Comment by a0viedo** [comment]
I know @gyaresu from the NodeSchool community, +1 on adding him.

**Comment by a0viedo** [comment]
@workshopper/core

**Comment by SomeoneWeird** [comment]
Fine by me.

**Comment by ralphtheninja** [comment]
Invitation sent.
