### ISSUE TITLE
Adding new members

### ISSUE THREAD

**Issue by martinheidegger** [workshopper/org#4]
Thinking of adding @marocchino @sethvincent @someoneweird and @a0viedo as owners here to increase the active members with stakes. What do you think?

**Comment by a0viedo** [comment]
Would be great :) I'm overwhelmed with a lot of things at the moment, but I will find time to dedicate on this.

**Comment by julianduque** [comment]
@martinheidegger sure, it's a great idea

**Comment by SomeoneWeird** [comment]
For sure, would love to help :)

**Comment by martinheidegger** [comment]
Invite sent! Please help improve @workshoppers!
