### ISSUE TITLE
JOIN

### ISSUE THREAD

**Issue by liashchynskyi** [workshopper/org#42]
Hello, guys) could I become a member of this organization?

**Comment by martinheidegger** [comment]
Hello @liashchynskyi, yes it is possible to join this organization though I think it would be better if you first show your investment into the workshopper org. What issues have you been working on? How do you intend to contribute?

cc. @workshopper/core

**Comment by ralphtheninja** [comment]
![screenshot from 2018-03-09 12-56-09](https://user-images.githubusercontent.com/308049/37206585-84455bca-2399-11e8-9d44-0f46d85faa65.png)

My guess is there will be no reply to this.

**Comment by martinheidegger** [comment]
I didn't want to jump to easy conclusions

**Comment by liashchynskyi** [comment]
@martinheidegger ok, thanks for the advice 🥇
