### ISSUE TITLE
Typo due to deprecated tab on the Chrome dev tools

### ISSUE THREAD

**Issue by aziz-boudi4** [workshopper/org#43]
Hello,

on the last exercise of `scope-chains-closures` called `Garbage Collection`:

- Step number 2 of the exercise prompt the user to `Open the DevTools > Timeline tab`, but I believe that the `Timeline tab` has been deprecated from the latest `Google Chrome` and it has been replaced by the `Performance` tab.

- I think it can be confusing for some people as they might waste time looking for the unexistent `Timeline tab`.

I'm happy to open a pull request and fix this issue.

**Comment by martinheidegger** [comment]
Please open a PR. There is a separate issue tracker for scope-chains-closures here: https://github.com/workshopper/scope-chains-closures/issues
