### ISSUE TITLE
Workshoppers npm org

### ISSUE THREAD

**Issue by finnp** [workshopper/org#44]
Hey,

I created a [workshoppers](https://www.npmjs.com/org/workshoppers) org to move workshoppers there in case there aren't many people that have access to the original workshop.

In case anyone wants access to it let me know.

Also if anyone owns the organisations or accounts `workshopper` or `nodeschool` let me know. I think they would be nice than workshoppers.

**Comment by martinheidegger** [comment]
There is a [workshopper](https://www.npmjs.com/org/workshopper) organization, I invited you as admin. I also "reserved" the "nodeschool" username a long time ago. I asked the npm team to convert that account into a username.

**Comment by finnp** [comment]
Cool, thanks. I think you can actually convert a user to an org on the website: https://www.npmjs.com/org/upgrade

**Comment by martinheidegger** [comment]
@finnp Okay done!
