### ISSUE TITLE
Enable workshopper/adventure on Travis

### ISSUE THREAD

**Issue by cristianberroeta** [workshopper/org#50]
Please enable [workshopper/adventure](https://github.com/workshopper/adventure) on [Travis](https://travis-ci.org/workshopper/adventure). The [.travis.yml](https://github.com/workshopper/adventure/blob/master/.travis.yml) file was recently committed.

Is this the right place to ask for enabling a repo on Travis?

cc. @workshopper/deploy

**Comment by martinheidegger** [comment]
Done: https://travis-ci.org/workshopper/adventure/builds/564734571

**Comment by martinheidegger** [comment]
Oh: This is the right repo to ask for this!
