### ISSUE TITLE
Publish polish translations

### ISSUE THREAD

**Issue by martinheidegger** [workshopper/org#6]
@workshopper/deploy (@julianduque) I just merged polish translations for learnyounode, workshopper and workshopper-exercise. Could you check them and publish them?

**Comment by martinheidegger** [comment]
@julianduque ping @rvagg ping
the deploy system is not working :wink:

**Comment by rvagg** [comment]
I had a chat with @julianduque and for the moment he's as busy as me so I've gone ahead and added @martinheidegger as publisher for the relevant packages. It'd be appreciated if you could sign your releases with a PGP tag using `npm config set sign-git-tag=true` and then using `npm version <whatever>` to increment versions (it should ask for your PGP password if it's set up properly).

**Comment by martinheidegger** [comment]
Thank you @rvagg

**Comment by a0viedo** [comment]
@martinheidegger can this be closed? I know the relevant discussion is taking place at https://github.com/workshopper/organizers/issues/2

**Comment by martinheidegger** [comment]
I really have to take rods comment closer to heart but let me close this issue.
