### ISSUE TITLE
Roadmap or Onboarding

### ISSUE THREAD

**Issue by iancrowther** [workshopper/org#9]
Hi All,

It's not clear to me what, if anything I could be doing to contribute.

Is there an objective for the workshopper org? When people ask what cool projects can i look at, this could be one of them.

**Comment by martinheidegger** [comment]
I feel like there should be an objective but until March 5th I am swarmed with tasks of higher priority.

**Comment by martinheidegger** [comment]
Hah!

**Comment by martinheidegger** [comment]
I have been talking with @jpwesselink to create an introductory video to get into the problems that workshopper-adventure is solving & why.

Also it would be good to work out this repo somehow.

**Comment by jpwesselink** [comment]
Let's share what's inside Martin's head :)

**Comment by martinheidegger** [comment]
First thing: I created https://github.com/workshopper/org/commit/80f9a72f1c3b8d6912495c818c8dd30f40b35128 to give a basic concept to start upon. Please send improvements as PR.
